name: attendence_monitoring_system
description: "A smart attendance monitoring application built with Flutter."
publish_to: 'none' # This is a private package.

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0' # Updated to a more flexible range

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Utility Packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0 # For date/time formatting (e.g., 'Tuesday, October 26')

  # State Management (As per our architecture)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5 # For cleaner provider syntax (optional but recommended)

  # UI Components
  fl_chart: ^0.68.0 # For building charts and graphs (Reports & Dashboard)
  table_calendar: ^3.1.2 # For the employee's attendance calendar screen
  
  # Add any other utilities you might need, e.g., for icons
  # flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

  # For Riverpod code generation (optional but recommended)
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true

  # Enable generation for internationalization (good practice for future features)
  generate: true

  # Define your asset paths here.
  assets:
    - assets/images/
    # - assets/icons/